Homework 8
pavelkhlebchik/mk-zarmarathon pull request #9
Opened 2021-06-17 15:36 UTC by pavelkhlebchik

2021-06-17 17:43 UTC, pavelkhlebchik commented
Осталось допилить game

2021-06-18 11:23 UTC, pavelkhlebchik commented
Осталось переписать генератор логов (разделить на функции)

2021-06-18 15:05 UTC, ZarMarathon requested changes
жду класс Game

2021-06-18 15:05 UTC, ZarMarathon commented on log.js
>  			$chat.insertAdjacentHTML(`afterbegin`, chatText);
брейк в дефолтном тоже нужен

2021-06-18 15:19 UTC, pavelkhlebchik commented on log.js
>  			$chat.insertAdjacentHTML(`afterbegin`, chatText);
Поправил)

2021-06-18 15:19 UTC, pavelkhlebchik reviewed
готово

2021-06-20 22:30 UTC, ZarMarathon approved these changes
аппрув

2021-06-20 22:30 UTC, ZarMarathon commented on game.js
> +			const enemyAttack = () => {
вот эти все функции сделай методами, они все здесь не нужны, иначе теряется весь смысл классов

2021-06-20 22:30 UTC, ZarMarathon commented on game.js
> +		this.start = () => {
это не нужно в конструкторе писать, пиши как метод как я показывал в уроке

2021-06-21 07:35 UTC, merged